name: Eli Overbey
description: Things I've written over the years

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: 'https://www.elioverbey.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://www.elioverbey.com/'
author:         'Eli Overbey'
