name: Eli Overbey
description: Things I've written over the years

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: https://www.elioverbey.com
domain_name: 'https://www.elioverbey.com'
google_analytics: 'UA-42487931-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://www.elioverbey.com/'
author:         'Eli Overbey'
