name: Eli Overbey
description: Things I've written over the years

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: 'https://www.elioverbey.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://www.elioverbey.com/'
author:         'Eli Overbey'


# Site settings
title: Eli Overbey
description: Revenue Operations
baseurl: ""
url: "https://www.elioverbey.com/"

# Personal Information
name: Eli Overbey
tagline: Revenue Operations
location: Raleigh-Durham-Chapel Hill Area
email: eli@example.com
phone: "+1 (555) 123-4567"
linkedin: "https://www.linkedin.com/in/elioverbey/"

# Social Links
social:
  linkedin: elioverbey
  twitter: elioverbey
  github: elioverbey

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  experiences:
    output: false
  education:
    output: false
  skills:
    output: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/